# Funciones para string siguiendo el primer ejercicio del libro
cadena1 = input("Introduzca la primera cadena:")
cadena2 = input("Introduzca la segunda cadena:")
cadena3 = input("Introduzca la tercera cadena:")

print("Longitud ed la cadena2 (len):", len(cadena2))
print("cadena3 toda en mayúscula (upper):", cadena3.upper())
print("cadena3 toda en minúscula (lower):", cadena3.lower())
print("cadena2 cambia de minúscula a mayúscula y viceversa (swapcase):", cadena2.swapcase())
print("cadena1 la primera en mayúscula (capitalize):", cadena1.capitalize())
print("cadena2 la primera de cada palabra a mayúscula (title):", cadena2.title())
print("¿la cadena1 esta toda en minúscula? (islower):", cadena1.islower())
print("¿la cadena1 esta toda en mayúscula? (isupper):", cadena1.isupper())
print("¿en la cadena2 todos los caracteres son imprimibles? (isprintable):", cadena2.isprintable())
print("¿cadena3 son todos alfanuméricos? (isalnum):", cadena3.isalnum())
print("¿cadena1 son todos alfabéticos? (isalpha):", cadena1.isalpha())
print("¿cadena3 la primera letra de cada palabra es mayuscula y ls demas minusculas? (istitle):", cadena3.istitle())
print("¿cadena2 todos los caracteres son espacios? (isspace):", cadena2.isspace())
print("¿cadena1 todos son dígitos? (isdigit):", cadena1.isdigit())
print("¿cadena2 todos los caracteres con representacion numérica? (isnumeric):", cadena2.isnumeric())
print("¿cadena3 todos los caracteres son numericos con representacion decimal? (isdecimal)", cadena3.isdecimal())
print("caracter mas alto de la cadena1 (max):", max(cadena1))
print("caracter mas bajo de la cadena3 (min):", min(cadena3))

