tupla = ('casa','2',99,345,'Perro',99)
tupla2 = (1,2,3,4,5,6,7,8,9)
print("Elementos de la tupla:", tupla)
print("Número de elementos 99:", tupla.count(99))
print("Posición que ocupa el elemento Perro:", tupla.index('Perro'))
print("Elemento tupla [0]:", tupla[0])
print("Elemento tupla [1]:", tupla[1])
print("Elemento tupla [2]:", tupla[2])
print("Elemento tupla [3]:", tupla[3])
print("Elemento tupla [4]:", tupla[4])
print("Elemento tupla [5]:", tupla[5])
print("tupla2 completa:", tupla2)
print("tupla2 rango [4:9]:", tupla2[4:9])
print("tupla2 rango [:3]:", tupla2[:3])
print("tupla2 rango [2:]:", tupla2[2:])
print("Concatenando las tuplas:", tupla + tupla2)
print("Multiplicando tuplas:", tupla2 * 3)